databases:
  - name: moneymate-mongo
    databaseName: moneymate
    plan: free

services:
  - type: web
    name: moneymate-api
    runtime: node
    region: oregon
    directory: server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: mongo_url
        fromDatabase:
          name: moneymate-mongo
          property: connectionString
      - key: jwt_secret
        generateValue: true
      - key: stripe_key
        sync: false
